"""add url_check_log table

Revision ID: 2060f63320c5
Revises: d7e21add232f
Create Date: 2026-04-16 12:30:50.261117

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2060f63320c5'
down_revision: str | Sequence[str] | None = 'd7e21add232f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_check_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_ok', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_check_log_entity_id'), 'url_check_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_url_check_log_entity_type'), 'url_check_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_url_check_log_is_ok'), 'url_check_log', ['is_ok'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_check_log_is_ok'), table_name='url_check_log')
    op.drop_index(op.f('ix_url_check_log_entity_type'), table_name='url_check_log')
    op.drop_index(op.f('ix_url_check_log_entity_id'), table_name='url_check_log')
    op.drop_table('url_check_log')
    # ### end Alembic commands ###
