"""init providers products users events audit

Revision ID: d7e21add232f
Revises: 
Create Date: 2026-04-16 11:54:16.886927

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd7e21add232f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_color', sa.String(length=16), nullable=True),
    sa.Column('provider_type', sa.Enum('BANK', 'MFO', 'FINTECH', 'ISLAMIC', name='provider_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NEEDS_VERIFICATION', 'DEPRECATED', 'COMING_SOON', name='provider_status'), nullable=False),
    sa.Column('license_body', sa.String(length=64), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('license_date', sa.Date(), nullable=True),
    sa.Column('license_url', sa.String(length=500), nullable=True),
    sa.Column('description_uz', sa.Text(), nullable=True),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('source_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('language', sa.Enum('UZ', 'RU', 'EN', name='user_language'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'VIEWER', 'EDITOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_admin_id'), 'admin_audit_log', ['admin_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('min_limit_uzs', sa.BigInteger(), nullable=True),
    sa.Column('max_limit_uzs', sa.BigInteger(), nullable=True),
    sa.Column('min_term_months', sa.Integer(), nullable=True),
    sa.Column('max_term_months', sa.Integer(), nullable=True),
    sa.Column('allowed_terms', sa.JSON(), nullable=True),
    sa.Column('is_interest_free', sa.Boolean(), nullable=False),
    sa.Column('markup_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('markup_note_uz', sa.Text(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('citizenship_required', sa.String(length=64), nullable=True),
    sa.Column('min_income_uzs', sa.BigInteger(), nullable=True),
    sa.Column('eligibility_note_uz', sa.Text(), nullable=True),
    sa.Column('use_case', sa.Enum('ONLINE', 'OFFLINE', 'UNIVERSAL', 'CASH', 'AUTO', name='product_use_case'), nullable=True),
    sa.Column('description_uz', sa.Text(), nullable=True),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('ios_app_url', sa.String(length=500), nullable=True),
    sa.Column('android_app_url', sa.String(length=500), nullable=True),
    sa.Column('telegram_bot', sa.String(length=128), nullable=True),
    sa.Column('telegram_channel', sa.String(length=128), nullable=True),
    sa.Column('support_phone', sa.String(length=64), nullable=True),
    sa.Column('support_email', sa.String(length=128), nullable=True),
    sa.Column('partners_count', sa.Integer(), nullable=True),
    sa.Column('partners_list_url', sa.String(length=500), nullable=True),
    sa.Column('source_cited_urls', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'NEEDS_VERIFICATION', 'INACTIVE', name='product_status'), nullable=False),
    sa.Column('source_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_provider_id'), 'products', ['provider_id'], unique=False)
    op.create_table('bot_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('START', 'VIEW_LIST', 'VIEW_PROVIDER', 'VIEW_PRODUCT', 'CLICK_OFFICIAL_LINK', 'SEARCH_BY_AMOUNT', 'COMPARE', 'LANGUAGE_CHANGE', 'FEEDBACK', name='bot_event_type'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_events_event_type'), 'bot_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_bot_events_product_id'), 'bot_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_bot_events_user_id'), 'bot_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_events_user_id'), table_name='bot_events')
    op.drop_index(op.f('ix_bot_events_product_id'), table_name='bot_events')
    op.drop_index(op.f('ix_bot_events_event_type'), table_name='bot_events')
    op.drop_table('bot_events')
    op.drop_index(op.f('ix_products_provider_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_admin_audit_log_admin_id'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
